kernel:
  image: linuxkit/kernel:4.9.58
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:6b3755e47f00d6027321d3fca99a19af6504be75
  - linuxkit/runc:52f92cb577879ce4cfe4e89be2d63af82523fc92
  - linuxkit/containerd:ed8e8f92e24dd4b94260cf147594ae3fd13a2182
  - linuxkit/ca-certificates:ea3c4c120f929f4f07ac8535d75933365b5e9582
onboot:
  - name: sysctl
    image: linuxkit/sysctl:1644bf07edbcaf5ce0bb764fa925b544183547f9
  - name: sysfs
    image: linuxkit/sysfs:3ae01a25583ee37a5ff8b09a0e569cb4bd8cf2e9
  - name: dhcpcd
    image: linuxkit/dhcpcd:aa685261ceb2557990dcfe9dd8824c6b9ec416e2
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:be811ded880af37a916f23bc9ddb274026ccc514
  - name: mount
    image: linuxkit/mount:96ac4d32d340ac6e4ddfbf506fa3a497d23649da
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: rngd
    image: linuxkit/rngd:45ed7759dd927f4cce3863073ea2e0da1d52a427
  - name: ntpd
    image: linuxkit/openntpd:0d7befc79842849d0b88d6c3b64200e340d7cf67
  - name: docker
    image: docker:17.07.0-ce-dind
    capabilities:
     - all
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /var/run:/var/run
     - /etc/html:/var/html
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: compose
    image: linuxkitprojects/compose:0535e78608f57702745dfd56fbe78d28d237e469
    binds:
     - /var/run:/var/run
     - /etc/compose:/compose
files:
  - path: etc/html/a/index.html
    source: html-a.html
  - path: etc/html/b/index.html
    source: html-b.html
  - path: etc/compose/docker-compose.yml
    source: docker-compose.yml
trust:
  org:
    - linuxkit
